#!/bin/bash
# -*- coding: utf-8 -*-

# ENTER PASSWORDS =========================================================================================
while true; do
echo -en "\n\e[1;36mEnter new root password [\e[1;33mMin. 8 chars\e[1;36m]: "; read -rs ROOT_PASS
echo -en "\n\e[1;37mRepeat root password [\e[1;33mMin. 8 chars\e[1;37m]: "; read -rs ROOT_PASS_REPEAT

[[ "${ROOT_PASS}" != "${ROOT_PASS_REPEAT}" ]] && echo -e "\n\e[1;31mPasswords do not match" && continue

[[ ! ${#ROOT_PASS} -ge 8 ]] && echo -e "\n\e[1;31mPassword for \e[1;33m\"root\"\e[1;31m does not meet requirements" || break
done
echo -e "\n\e[1;32mPassword accepted"

while true; do
echo -en "\n\e[1;36mEnter Pi-Hole new root password [\e[1;33mMin. 8 chars\e[1;36m]: "; read -rs PIHOLE_PASS
echo -en "\n\e[1;37mRepeat Pi-Hole root password [\e[1;33mMin. 8 chars\e[1;37m]: "; read -rs PIHOLE_PASS_REPEAT

[[ "${PIHOLE_PASS}" != "${PIHOLE_PASS_REPEAT}" ]] && echo -e "\n\e[1;31mPasswords do not match" && continue

[[ ! ${#PIHOLE_PASS} -ge 8 ]] && echo -e "\n\e[1;31mPassword for Pi-Hole user \e[1;33m\"root\"\e[1;31m does not meet requirements" || break
done
echo -e "\n\e[1;32mPassword accepted"

# PREPARE DISK ============================================================================================
DISKS="$(lsblk -ln | grep disk | cut -d' ' -f1)"
echo -e "\n\e[1;34mDisks:\n\e[1;33m${DISKS}"

while true; do
echo -en "\n\e[1;36mEnter disk name for installation [\e[1;33msda, nvme0n1, mmcblk0, ...\e[1;36m]:\e[1;33m "; read -r DISK_R
DISK=$(echo "${DISK_R}" | tr '[:upper:]' '[:lower:]')
[[ ! -n "$(echo "${DISKS}" | grep -ow "${DISK}")" ]] && echo -e "\e[1;31mDisk name not found" || break
done

while true; do
echo -en "\n\e[1;31mAll data on disk \e[1;33m\"${DISK}\"\e[1;31m will be destroyed. \e[1;35mContinue? [\e[1;32myes\e[1;37m/\e[1;31mno\e[1;35m]:\e[1;33m "; read -r DESTROY
[[ "${DESTROY}" =~ ^([yY][eE][sS])$ ]] && break
[[ "${DESTROY}" =~ ^([nN][oO])$ ]] && exit 0
done

echo -e "\e[0m"

echo -e "g\nw\n" | fdisk /dev/"${DISK}"
echo -e 'mkpart "EFI system partition" fat32 1MiB 501MiB\nset 1 esp on\nmkpart "SYSTEM" ext4 501MiB 100%\nq\n' | parted "/dev/${DISK}"

PARTS=()
while IFS='' read -r line; do PARTS+=("$line"); done < <(lsblk -ln /dev/"${DISK}" | grep part | cut -d' ' -f1)
echo "${DISK}"
echo "${PARTS[@]}" | tr ' ' '\n'

# FORMAT ==================================================================================================
mkfs.vfat /dev/"${PARTS[0]}"                        # EFI   (/dev/nvme0n1p1)
echo -e "y\n" | mkfs.ext4 /dev/"${PARTS[1]}"        # root  (/dev/nvme0n1p2)

# MOUNT ===================================================================================================
mount /dev/"${PARTS[1]}" /mnt            # root  (/dev/nvme0n1p2)
mkdir /mnt/boot
mount /dev/"${PARTS[0]}" /mnt/boot       # EFI   (/dev/nvme0n1p1)

# ARCH ====================================================================================================
sed -i '/Color/c\Color' /etc/pacman.conf
sed -i '/ParallelDownloads/c\ParallelDownloads = 25' /etc/pacman.conf

pacstrap /mnt base linux-firmware linux linux-headers efibootmgr mc nano msedit dhcpcd ntp

genfstab /mnt >> /mnt/etc/fstab

# SETUP ===================================================================================================
setup() {
cat << STP > /mnt/INST_ARCH_PIHOLE
#!/bin/bash
# -*- coding: utf-8 -*-

ROOT_PASS=${ROOT_PASS}
PIHOLE_PASS=${PIHOLE_PASS}

DISK=${DISK}
PARTS=${PARTS[@]}

# PACKAGES ================================================================================================
sed -i '/Color/c\Color' /etc/pacman.conf
sed -i '/ParallelDownloads/c\ParallelDownloads = 25' /etc/pacman.conf

# ANDONTIE AUR
pacman-key --recv-key 72BF227DD76AE5BF
pacman-key --lsign-key 72BF227DD76AE5BF

cat << 'EOF' >> /etc/pacman.conf

[andontie-aur]
Server = https://aur.andontie.net/\$arch
EOF

pacman -Syu --noconfirm

# NETWORK =================================================================================================
systemctl enable dhcpcd

echo "pi-hole" > /etc/hostname

cp /etc/dhcpcd.conf /etc/dhcpcd.conf.bak

cat << EOF > /etc/dhcpcd.conf
interface $(ip r | awk '/default/ {print $5}')
static ip_address=192.168.1.3/24
static routers=192.168.1.1
static domain_name_servers=1.0.0.1
EOF

sed -i '/DNSStubListener/c\DNSStubListener=no' /etc/systemd/resolved.conf

echo -e "${ROOT_PASS}\n${ROOT_PASS}" | passwd

# GRUB ====================================================================================================
efibootmgr -c -d /dev/"${DISK}" -p 1 -L "ArchLinux" -l \vmlinuz-linux -u "root=/dev/${PARTS[1]} rw initrd=/initramfs-linux.img"

# TIME ====================================================================================================
systemctl enable ntpd

ln -sf /usr/share/zoneinfo/"$(echo -e '5\n23\n1\n1' | tzselect)" /etc/localtime

# PIHOLE ==================================================================================================
pacman -S pi-hole-core --noconfirm

echo -e "${PIHOLE_PASS}\n${PIHOLE_PASS}" | pihole setpassword

# END  ====================================================================================================
echo -e "\nResults ==================================================\n\nDisk partitions:"; lsblk -o +FSUSED;
echo -e "\nDisk space:"; df -h /; echo -e "\nNetwork interfaces:"; ip -br a; echo -e "\nMemory usage:"; free -h

exit

STP
}
# END SETUP ===============================================================================================

echo -e "$(setup)"

chmod -R 0777 /mnt/INST_ARCH_PIHOLE

echo -e "./INST_ARCH_PIHOLE" | arch-chroot /mnt

rm /mnt/INST_ARCH_PIHOLE

# MOUNT REMOTE STORAGE ====================================================================================
mkdir -m777 /GIT
sudo mount -t cifs //192.168.1.11/DOWNLOAD_TMP /GIT -o username=lexx,password=lexx,iocharset=utf8,file_mode=0777,dir_mode=0777

# CREATE BACKUP IN REMOTE STORAGE WITH TAR ARCHIVER =======================================================
cd /mnt
tar -cvpzf /GIT/arch-pihole_lxc.tar.gz --one-file-system ./*
cd /

umount -R /mnt

reboot
